In [1]:
import pandas as pd

In [24]:
df= pd.read_excel('cust_data.xlsx')
df

       Cust_ID Gender  Orders  Jordan  ...  Colavita  Microsoft  Jiffy mix  Kraft
0            1      M       7       0  ...         0          0          0      0
1            2      F       0       0  ...         0          0          0      0
2            3      M       7       0  ...         0          1          0      0
3            4      F       0       0  ...         0          0          0      0
4            5    NaN      10       0  ...         0          0          1      1
...        ...    ...     ...     ...  ...       ...        ...        ...    ...
29995    29996      M       0       0  ...         0          0          0      0
29996    29997      M       1       0  ...         0          0          0      0
29997    29998      M       0       0  ...         0          0          0      0
29998    29999      M       0       0  ...         0          0          0      0
29999    30000      F       3       2  ...         0          0          0      0

[30000 rows x 38 columns]

In [25]:
df.isna().sum()

Cust_ID                      0
Gender                    2724
Orders                       0
Jordan                       0
Gatorade                     0
Samsung                      0
Asus                         0
Udis                         0
Mondelez International       0
Wrangler                     0
Vans                         0
Fila                         0
Brooks                       0
H&M                          0
Dairy Queen                  0
Fendi                        0
Hewlett Packard              0
Pladis                       0
Asics                        0
Siemens                      0
J.M. Smucker                 0
Pop Chips                    0
Juniper                      0
Huawei                       0
Compaq                       0
IBM                          0
Burberry                     0
Mi                           0
LG                           0
Dior                         0
Scabal                       0
Tommy Hilfiger               0
Hollister                    0
Forever 21                   0
Colavita                     0
Microsoft                    0
Jiffy mix                    0
Kraft                        0
dtype: int64

In [26]:
df['Gender'] = df['Gender'].fillna(0)

In [27]:
df

       Cust_ID Gender  Orders  Jordan  ...  Colavita  Microsoft  Jiffy mix  Kraft
0            1      M       7       0  ...         0          0          0      0
1            2      F       0       0  ...         0          0          0      0
2            3      M       7       0  ...         0          1          0      0
3            4      F       0       0  ...         0          0          0      0
4            5      0      10       0  ...         0          0          1      1
...        ...    ...     ...     ...  ...       ...        ...        ...    ...
29995    29996      M       0       0  ...         0          0          0      0
29996    29997      M       1       0  ...         0          0          0      0
29997    29998      M       0       0  ...         0          0          0      0
29998    29999      M       0       0  ...         0          0          0      0
29999    30000      F       3       2  ...         0          0          0      0

[30000 rows x 38 columns]

In [28]:

df['Gender'] = df['Gender'].replace(['M','F'],[1,2])

In [29]:
df

       Cust_ID  Gender  Orders  Jordan  ...  Colavita  Microsoft  Jiffy mix  Kraft
0            1       1       7       0  ...         0          0          0      0
1            2       2       0       0  ...         0          0          0      0
2            3       1       7       0  ...         0          1          0      0
3            4       2       0       0  ...         0          0          0      0
4            5       0      10       0  ...         0          0          1      1
...        ...     ...     ...     ...  ...       ...        ...        ...    ...
29995    29996       1       0       0  ...         0          0          0      0
29996    29997       1       1       0  ...         0          0          0      0
29997    29998       1       0       0  ...         0          0          0      0
29998    29999       1       0       0  ...         0          0          0      0
29999    30000       2       3       2  ...         0          0          0      0

[30000 rows x 38 columns]

In [49]:
from sklearn.cluster import KMeans
km = KMeans(n_clusters = 3, random_state=90)
km.fit(df.drop('Gender', axis=1))

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=90, tol=0.0001, verbose=0)

In [50]:
km.cluster_centers_

array([[5.01400000e+03, 4.03680064e+00, 2.12426449e-01, 2.33469632e-01,
        1.64954623e-01, 1.18081181e-01, 1.00528573e-01, 1.10800838e-01,
        8.27765034e-02, 1.13294106e-01, 7.78896978e-02, 1.17881719e-01,
        3.01286526e-01, 2.23995213e-01, 1.15887105e-01, 8.89598085e-02,
        9.86336890e-02, 2.93008876e-01, 6.32292809e-02, 7.37807919e-01,
        2.11628603e-01, 5.00049865e-01, 2.47431934e-01, 1.27655331e-01,
        4.94664406e-02, 3.49755660e-01, 1.33539444e-01, 9.56417672e-02,
        2.17113793e-01, 3.23526479e-01, 1.57574549e-01, 4.84691333e-02,
        4.41807121e-02, 1.93078688e-01, 1.18081181e-01, 9.32482298e-02,
        5.85419368e-02, 1.60955420e+00, 1.60955420e+00],
       [2.50140000e+04, 4.31144089e+00, 3.36007219e-01, 2.66319061e-01,
        2.89080517e-01, 1.98736589e-01, 1.91918179e-01, 1.55720445e-01,
        1.29148701e-01, 1.23633811e-01, 8.40268726e-02, 1.63341021e-01,
        3.45232127e-01, 2.00140379e-01, 1.71162138e-01, 1.72064574e-01,
        1.10698887e-01, 2.95999198e-01, 3.54958388e-02, 7.61255390e-01,
        2.86674020e-01, 4.47809085e-01, 2.82663191e-01, 1.18520004e-01,
        2.38644340e-02, 4.96239848e-01, 9.67612554e-02, 1.24937331e-01,
        3.25077710e-01, 4.10508373e-01, 1.69156723e-01, 1.19121628e-01,
        7.89130653e-02, 1.92820616e-01, 1.17517297e-01, 7.79103580e-02,
        8.93412213e-02, 1.67281660e+00, 1.67281660e+00],
       [1.50275000e+04, 4.16190000e+00, 2.54200000e-01, 2.57300000e-01,
        2.15100000e-01, 1.67400000e-01, 1.38400000e-01, 1.52900000e-01,
        1.09000000e-01, 9.74000000e-02, 1.20900000e-01, 1.39300000e-01,
        3.38200000e-01, 2.03800000e-01, 1.37500000e-01, 2.22500000e-01,
        1.09000000e-01, 3.11700000e-01, 4.54000000e-02, 7.65400000e-01,
        2.45600000e-01, 4.64500000e-01, 2.44000000e-01, 1.10100000e-01,
        2.25000000e-02, 4.38500000e-01, 1.33600000e-01, 8.71000000e-02,
        2.71500000e-01, 3.76400000e-01, 1.50200000e-01, 6.56000000e-02,
        4.90000000e-02, 1.90700000e-01, 1.13500000e-01, 9.29000000e-02,
        6.49000000e-02, 1.65080000e+00, 1.65080000e+00]])

In [51]:
df['Cluster'] = df['Gender']

In [52]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(df['Cluster'],km.labels_))
print(classification_report(df['Cluster'],km.labels_))

[[ 944  887  893]
 [2025 1490 1707]
 [7051 7603 7400]]
              precision    recall  f1-score   support

           0       0.09      0.35      0.15      2724
           1       0.15      0.29      0.20      5222
           2       0.74      0.34      0.46     22054

    accuracy                           0.33     30000
   macro avg       0.33      0.32      0.27     30000
weighted avg       0.58      0.33      0.39     30000